name: Auto Fetch IPTV Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Full M3U Playlist
        run: |
          # Xtream Codes API থেকে সরাসরি আসল M3U প্লেলিস্ট সেভ করার কমান্ড
          curl -L -A "IPTVSmarters/1.0.3" "http://filex.me:8080/get.php?username=3114654477&password=5787654467&type=m3u_plus&output=ts" -o playlist.m3u8

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u8
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update IPTV playlist" && git push)
